import Head from 'next/head';
import Image from 'next/image';
import AboutMe from '../components/AboutMe';
import Contact from '../components/Contact';
import Footer from '../components/Footer';
import Hero from '../components/Hero';
import MessageSection from '../components/MessageSection';
import RecentWork from '../components/RecentWork';
import TalkTech from '../components/TalkTech';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <MessageSection />
      <RecentWork />
      <AboutMe />
      <TalkTech />
      <Contact />
      <Footer />
    </div>
  );
}
